
server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://47.99.175.70:3306/test
    username: rootroot
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.springboottest1.entity  # 注意：对应实体类的路径